### ISSUE TITLE
Fix VTL Stack

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vtl#18]
There are some commented tests in this [file](https://github.com/vlang/vtl/blob/main/stack_test.v). We need to fix the implementation of each related function

**Comment by ulises-jeremias** [comment]
@cmnemoi hey! I saw you are contributing on VTL! probably this one can be challenging! Let me know if you want to take a look and you need any help on it!

**Comment by cmnemoi** [comment]
Hey @ulises-jeremias,. I will take a look.

**Comment by cmnemoi** [comment]
Given my first investigations, I think there is a bug in `vtl.assignement.assign()` (which is untested) :

```v
module main

import vtl

fn main()
{

	test_tensor := vtl.from_array([1,2,3,4,5,6,7,8], [2, 4])
	zeros := vtl.zeros<int>([2,2])

	mut slice := test_tensor.slice_hilo([0,0], [2,2])

	println("slice to replace = \n$slice")
	/*
		slice_to_repalce =
		&[[1, 2], 
		[5, 6]]
	*/
	println("replacement = \n$zeros")
	/*	
		zeros = 
		&[[0, 0], 
		[0, 0]]
	*/
	
	slice.assign(zeros)

	println("new slice = \n$slice  \n(should be \n$zeros)")
	/*

		new slice = 
		&[[0, 0], 
		[5, 6]]  

		(should be 
		&[[0, 0], 
		[0, 0]])
	*/

	assert zeros == slice
}
```

I will investigate further
