### ISSUE TITLE
autograd:register Inconsistency between use[p27,.....] and definition[p74]

### ISSUE THREAD

**Issue by Yonua** [vlang/vtl#25]
![image](https://user-images.githubusercontent.com/101091874/187941955-7b0f79de-0660-496e-a068-d2cc124cefc1.png)

https://github.com/vlang/vtl/blob/3e759426769bb77facea4037166ba30a0d1160d7/autograd/context.v#L74
https://github.com/vlang/vtl/blob/3e759426769bb77facea4037166ba30a0d1160d7/autograd/gates_basic.v#L27

**Comment by ulises-jeremias** [comment]
hey! thanks for opening this issue! I just solved it on latest commit 👌🏻
