### ISSUE TITLE
transpose(`.t()`) doesn't work

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/vtl#7]
**VTL version:** 
master

**OS:** 
win10

**What did you do?**
```V
import vtl

fn main() {
	println(vtl.ones([2,2]).t())
}
```

**What did you expect to see?**
a 2*2 matrix with elements 1.0
 
**What did you see instead?**
```
[[0e+00, 0e+00],
[0e+00, 0e+00]]
```

**Comment by ulises-jeremias** [comment]
@SleepyRoy same error as noticed on #8 . I have a fix and I'll push it asap
![image](https://user-images.githubusercontent.com/17727170/120868176-ca3a7a00-c569-11eb-9c19-0e7f72277b47.png)

**Comment by ulises-jeremias** [comment]
Solved on latest commit 👌🏻
