### ISSUE TITLE
random generator (`random()`) doesn't work

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/vtl#8]
**VTL version:**
master
 
**OS:** 
win10

**What did you do?**
```V
import vtl

fn main() {
	println(vtl.random(0,1,[2,2]))
}
```

**What did you expect to see?**
a 2*2 matrix with elements 0.0~1.0
 
**What did you see instead?**
```
[[0.949985009492209,             0e+00],
[            0e+00,             0e+00]]
```

**Comment by ulises-jeremias** [comment]
Hey! thanks for this great catch! I have a fix right now, it was due to some issues on the iterator. I'll test it more and then I'll push it to master.

![image](https://user-images.githubusercontent.com/17727170/120864670-f56d9b00-c562-11eb-8aec-2d807e498dbc.png)

**Comment by ulises-jeremias** [comment]
Solved on latest commit 👌🏻
